Fulcrum: add an ability to browse under someone's account
bZxNetwork/fulcrum_ui pull request #335
Opened 2020-11-10 18:01 UTC by Kharabet

2020-11-10 19:43 UTC, AoDev requested changes
Just saw some typos, but looks good otherwise. Nice refactor  : )

2020-11-10 19:43 UTC, AoDev commented on packages/fulcrum/src/layout/FooterVersion.tsx
> +import ImepsonateInput from '../components/ImpersonateImput'
Typo

```suggestion
import ImpersonateInput from '../components/ImpersonateInput'
```

2020-11-10 19:43 UTC, AoDev commented on packages/fulcrum/src/services/FulcrumProvider.ts
> +  public impersionateAddress = ''
```suggestion
  public impersonateAddress = ''
```

2020-11-10 19:43 UTC, AoDev commented on packages/fulcrum/src/services/FulcrumProvider.ts
> +    return this.impersionateAddress
```suggestion
    return this.impersonateAddress
```

Nice refactor :)

2020-11-10 19:43 UTC, AoDev commented on packages/fulcrum/src/components/ImpersonateImput.tsx
> +export function ImepsonateInput() {
typo
```suggestion
export function ImpersonateInput() {
```

2020-11-10 22:52 UTC, Kharabet commented
Oh... How come I made a typo...

2020-11-11 09:50 UTC, AoDev approved these changes
Cool 👍

2020-11-14 18:22 UTC, merged