Add warnings to Liquidation form about insufficient wallet balance
bZxNetwork/fulcrum_ui pull request #346
Opened 2020-11-23 23:28 UTC by Kharabet

2020-11-24 08:43 UTC, AoDev requested changes

2020-11-24 08:43 UTC, AoDev commented on packages/protocol-explorer/src/components/LiquidationForm.tsx
> +            className={`btn btn-submit action ${didSubmit || amountMsg ? `btn-disabled` : ``}`}>
The button should actually be disabled. Not just use a css class.

2020-11-25 10:33 UTC, Kharabet commented on packages/protocol-explorer/src/components/LiquidationForm.tsx
> +            className={`btn btn-submit action ${didSubmit || amountMsg ? `btn-disabled` : ``}`}>
Fixed

2020-11-26 11:57 UTC, AoDev approved these changes
Worked for me on local :)

2020-11-27 09:16 UTC, merged