TradeFrom stale data on Fulcrum
bZxNetwork/fulcrum_ui pull request #356
Opened 2020-11-30 10:17 UTC by OlehX

2020-11-30 10:17 UTC, OlehX commented
https://app.clubhouse.io/bzx1/story/519/tradefrom-stale-data-on-fulcrum

2020-11-30 13:43 UTC, AoDev commented
@OlehX What is the best way to test this without waiting?

2020-11-30 13:52 UTC, OlehX commented
@AoDev need to decrease 300000 ms delay inside window.SetTimeout

2020-11-30 14:18 UTC, AoDev requested changes

2020-11-30 14:18 UTC, AoDev commented on packages/fulcrum/src/components/TradeForm.tsx
> +      () => this._isMounted && this.setState({ ...this.state, isExpired: true }),
With `setState` you can do simply `this.setState({isExpired: true})` 

You dont need to copy the entire state to modify one property.

Spreading is only useful if you need to modify a nested object so that its reference changes and can be picked up by memo / pureComponent shallow comparison.

2020-11-30 14:18 UTC, AoDev commented on packages/fulcrum/src/components/TradeForm.tsx
> +              <button onClick={this.onUpdateClick} className={`trade-form__submit-button update`}>
There is no actual warning of why the button turns to "update". Shouldn't we have a small sentence like "Price has changed" or something similar? It might be weird for a user to just see "update".

2020-11-30 18:36 UTC, AoDev approved these changes

2020-12-01 08:13 UTC, OlehX commented
https://app.clubhouse.io/bzx1/story/1129/lendform-stale-data-on-fulcrum

2020-12-01 14:16 UTC, AoDev commented
@OlehX There is an issue with the text color in lend form 
<img width="580" alt="Screenshot 2020-12-01 at 15 15 08" src="https://user-images.githubusercontent.com/1526150/100751817-1b658780-33e8-11eb-9994-2a729655c549.png">

2020-12-02 17:04 UTC, merged